name: CI
on:
  pull_request_target:

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |-
            system-features = nixos-test benchmark big-parallel kvm uid-range
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check
