name: CI
on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |-
            system-features = nixos-test benchmark big-parallel kvm uid-range
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check
      - if: ${{ failure() }}
        run: |
          echo "::error :: Check failed, please run test locally for logs."
